language: php

php:
    - 5.3
    - 5.4

before_script:
    - sudo apt-get install php5-imap
    - sudo service apache2 restart
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install --dev
