language: php

php:
    - 5.3
    - 5.4

before_script:
    - sudo apt-get install php5-imap
    - echo "extension=imap.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install --dev
